services:
  postgres:
    image: postgres
    volumes:
      - ./V1_tables_create_sql.sql:/docker-entrypoint-initdb.d/V1_tables_create_sql.sql
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DATABASE: "tweeter"
